### ISSUE TITLE
Some datasets have an invalid date despite having good metadata

### ISSUE THREAD

**Issue by adamzerella** [magda-io/magda#1239]
### Problem description
E.g: https://search.data.gov.au/dataset/ds-aodn-a6722d0b-c11a-4395-aa8b-50f25dccf7d9 has an `Invalid date` yet the dataset it points to http://www.marlin.csiro.au/geonetwork/srv/eng/search#!a6722d0b-c11a-4395-aa8b-50f25dccf7d9 has valid metadata.

### Problem reproduction steps
Go to [dataset](https://search.data.gov.au/dataset/ds-aodn-a6722d0b-c11a-4395-aa8b-50f25dccf7d9) to observe `Invalid Date` then look at the reference.

### Screenshot / Design / File reference
# Dataset:
![image](https://user-images.githubusercontent.com/1501560/41577803-4ff10cc8-73d2-11e8-9806-43a9d27b7ee8.png)

# Metadata:
![image](https://user-images.githubusercontent.com/1501560/41577794-441f8a96-73d2-11e8-859a-488dab0eed45.png)

**Comment by nahidakbar** [comment]
TODO: ```TypeError: Cannot read property '0' of undefined
    at CswTransformer.getRawDatasetId (/home/god/magda/magda-csw-connector/dist/CswTransformer.js:49:47)
    at CswTransformer.getIdFromJsonDataset (/home/god/magda/magda-csw-connector/dist/CswTransformer.js:17:25)
    at CswTransformer.datasetJsonToRecord (/home/god/magda/magda-typescript-common/dist/JsonTransformer.js:49:25)
    at JsonConnector.<anonymous> (/home/god/magda/magda-typescript-common/dist/JsonConnector.js:88:49)
    at Generator.next (<anonymous>)
    at /home/god/magda/magda-typescript-common/dist/JsonConnector.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/god/magda/magda-typescript-common/dist/JsonConnector.js:3:12)
    at AsyncPage_1.forEachAsync (/home/god/magda/magda-typescript-common/dist/JsonConnector.js:87:88)
    at /home/god/magda/magda-typescript-common/dist/AsyncPage.js:115:19```
