### ISSUE TITLE
Indexer pod will exist when re-indexing data

### ISSUE THREAD

**Issue by jevy-wangfei** [magda-io/magda#1291]
### Problem description
Indexer consume really huge memory when re-indexing data, and the indexer pod will exist when it reaches the pod limitation. 
But when set the pod without limitation on memory and CPU usage, it will still exist with OutOfMemory Error

#### Log of existing when reach limitation
``` 
 
I  [INFO] [06/25/2018 03:15:14.169] [indexer-akka.actor.default-dispatcher-32] [akka.actor.ActorSystemImpl(indexer)] Successfully indexed 1 datasets
 
I  [INFO] [06/25/2018 03:15:14.183] [indexer-akka.actor.default-dispatcher-32] [akka.actor.ActorSystemImpl(indexer)] Successfully indexed 9 datasets
 
I  [INFO] [06/25/2018 03:15:27.080] [main] [IndexerApp$(akka://indexer)] Starting Indexer
 
I  [INFO] [06/25/2018 03:15:27.082] [main] [IndexerApp$(akka://indexer)] Log level is INFO
 
I  [INFO] [06/25/2018 03:15:27.675] [indexer-akka.actor.default-dispatcher-3] [akka.actor.ActorSystemImpl(indexer)] No password specified, starting without XPack
 
I  [INFO] [06/25/2018 03:15:35.974] [main] [IndexerApp$(akka://indexer)] Listening on 0.0.0.0:80
```
#### Log of existing with OutOfMemory Error
``` 

I  [INFO] [06/25/2018 08:52:21.601] [indexer-akka.actor.default-dispatcher-13] [akka.actor.ActorSystemImpl(indexer)] Successfully indexed 11 datasets
 
E  Uncaught error from thread [indexer-akka.actor.default-dispatcher-13] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[indexer]
 
E  java.lang.OutOfMemoryError: GC overhead limit exceeded
	at akka.stream.impl.fusing.GraphInterpreterShell$$anonfun$interpreter$1.apply(ActorGraphInterpreter.scala:327)
	at akka.stream.impl.fusing.GraphInterpreterShell$$anonfun$interpreter$1.apply(ActorGraphInterpreter.scala:326)
	at akka.stream.stage.GraphStageLogic$$anon$2.invoke(GraphStage.scala:912)
	at akka.stream.stage.GraphStageLogic$SubSinkInlet$$anonfun$5.apply(GraphStage.scala:1018)
	at akka.stream.stage.GraphStageLogic$SubSinkInlet$$anonfun$5.apply(GraphStage.scala:1018)
	at akka.stream.impl.fusing.SubSink$$anon$3.onPush(StreamOfStreams.scala:625)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:649)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:594)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:619)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:502)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
 
I  [INFO] [06/25/2018 08:52:44.182] [main] [IndexerApp$(akka://indexer)] Starting Indexer
 
I  [INFO] [06/25/2018 08:52:44.183] [main] [IndexerApp$(akka://indexer)] Log level is INFO
```

#### Screenshot of existing when reach limitation
![image](https://user-images.githubusercontent.com/6417796/41880870-d2fb85d4-7923-11e8-89c2-8653d2104560.png)

#### Screenshot of existing with OutOfMemory Error
![image](https://user-images.githubusercontent.com/6417796/41880863-c558ed18-7923-11e8-91bd-b36dfc4241c6.png)

**Comment by AlexGilleran** [comment]
Thanks for the report @jevy-wangfei - are you able to share the details of what it was trying to index when it did this? This might be related to https://github.com/magda-io/magda/issues/1068
