### ISSUE TITLE
DAP Connector Fails after a while

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1705]
### Problem description
When I run the DAP connector, it runs for a while but fails eventually:

```
>> request detail of https://data.csiro.au/dap/ws/v2/collections/csiro:10513
>> request distribution of https://data.csiro.au/dap/ws/v2/collections/11873/data 1
>> request distribution of https://data.csiro.au/dap/ws/v2/collections/11731/data 3
>> request distribution of https://data.csiro.au/dap/ws/v2/collections/11720/data 3
>> request distribution of https://data.csiro.au/dap/ws/v2/collections/11723/data 3
>> request distribution of https://data.csiro.au/dap/ws/v2/collections/11725/data 3
>> request distribution of https://data.csiro.au/dap/ws/v2/collections/11513/data 1
>> request distribution of https://data.csiro.au/dap/ws/v2/collections/11715/data 3
>> request distribution of https://data.csiro.au/dap/ws/v2/collections/11718/data 3
>> request distribution of https://data.csiro.au/dap/ws/v2/collections/11604/data 2
>> request distribution of https://data.csiro.au/dap/ws/v2/collections/11734/data 3
>> request distribution of https://data.csiro.au/dap/ws/v2/collections/11519/data 404
>> request distribution of https://data.csiro.au/dap/ws/v2/collections/11373/data 450
>> request distribution of https://data.csiro.au/dap/ws/v2/collections/11872/data 2
>> request distribution of https://data.csiro.au/dap/ws/v2/collections/11792/data 262
>> request distribution of https://data.csiro.au/dap/ws/v2/collections/11678/data 3
>> request distribution of https://data.csiro.au/dap/ws/v2/collections/11735/data 3
/usr/src/app/component/dist/Dap.js:187
                                    simpleData.data, detail.file.length);
                                                           ^

TypeError: Cannot read property 'file' of undefined
    at Request.request [as _callback] (/usr/src/app/component/dist/Dap.js:187:60)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:314:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
```

### Problem reproduction steps
Run the dap connector and wait

**Comment by aneesha09** [comment]
This needs an investigation. It is an intermittent problem.
