### ISSUE TITLE
Deploy can cause momentary elasticsearch downtime

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#1707]
### Problem description
When doing a deploy on prod, the search apis sometimes get stuck in a state where everything sent to them fails:

```
[INFO] [09/12/2018 05:56:48.196] [search-api-akka.actor.default-dispatcher-6] [akka.actor.ActorSystemImpl(search-api)] Successfully made initial contact with the ES client (this doesn't mean we're fully connected yet!)
[ERROR] [09/12/2018 05:58:02.485] [search-api-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(search-api)] Exception when searching
java.lang.RuntimeException: search_phase_execution_exception: all shards failed
	at au.csiro.data61.magda.search.elasticsearch.Exceptions.ESGenericException$.unapply(Exceptions.scala:54)
	at au.csiro.data61.magda.search.elasticsearch.ElasticSearchQueryer$$anonfun$search$2$$anonfun$apply$4.apply(ElasticSearchQueryer.scala:90)
	at au.csiro.data61.magda.search.elasticsearch.ElasticSearchQueryer$$anonfun$search$2$$anonfun$apply$4.apply(ElasticSearchQueryer.scala:79)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

It's unclear whether this is because the search api pods are getting stuck or whether the readness probe on the data nodes is saying that the data nodes are ok before they actually are.

**Comment by AlexGilleran** [comment]
Would probably be resolved by https://github.com/magda-io/magda/issues/696
