### ISSUE TITLE
magda-apidocs-server build literally makes a folder called $PWD on windows

### ISSUE THREAD

**Issue by maxious** [magda-io/magda#1772]
### Problem description
```
    "build": "generate-api-documentation --config $PWD/apidoc.json --output $PWD/build",
```
Literally makes a folder called $PWD/build in the working directory even when using lerna in the root of the project. As such, it's probably not needed any way but someone needs to test windows/linux lerna/yarn and from different folders. 

Work around is to copy the build folder after building.

### Problem reproduction steps
run lerna build/yarn build on Windows

### Screenshot / Design / File reference
```
lerna info Executing command in 31 packages: "yarn run docker-build-local"
lerna ERR! yarn run docker-build-local exited 1 in '@magda/apidocs-server'
lerna ERR! yarn run docker-build-local stdout:
yarn run v1.10.1
$ create-docker-context-for-node-component --build --push --tag auto --local
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run docker-build-local stderr:
fs.js:955
  binding.stat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, stat 'C:\Users\maxio\Documents\GitHub\magda\magda-apidocs-server\build'
    at Object.fs.statSync (fs.js:955:11)
    at Object.statSync (C:\Users\maxio\Documents\GitHub\magda\node_modules\graceful-fs\polyfills.js:297:22)
    at Object.copySync (C:\Users\maxio\Documents\GitHub\magda\scripts\node_modules\fs-extra\lib\copy-sync\copy-sync.js:31:86)
    at C:\Users\maxio\Documents\GitHub\magda\scripts\create-docker-context-for-node-component.js:309:21
    at Array.forEach (<anonymous>)
    at preparePackage (C:\Users\maxio\Documents\GitHub\magda\scripts\create-docker-context-for-node-component.js:262:10)
    at Object.<anonymous> (C:\Users\maxio\Documents\GitHub\magda\scripts\create-docker-context-for-node-component.js:79:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
error Command failed with exit code 1.
```

**Comment by AlexGilleran** [comment]
:|

**Comment by kring** [comment]
You can set the shell that is used on Windows to Bash (the default is cmd):

https://docs.npmjs.com/cli/run-script

> The actual shell your script is run within is platform dependent. By default, on Unix-like systems it is the /bin/sh command, on Windows it is the cmd.exe. The actual shell referred to by /bin/sh also depends on the system. As of npm@5.1.0 you can customize the shell with the script-shell configuration.
