### ISSUE TITLE
Need a way to run UI Only Preview in Gitlab

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#1829]
### Problem description

Currently, `UI Only Preview in Gitlab` won't run probably as web-server pod needs get the content of index.html from content API (`http://content-api/v0/includeHtml.text`).

We will see the following error:
```
{ FetchError: request to http://content-api/v0/includeHtml.text failed, reason: getaddrinfo ENOTFOUND content-api content-api:80
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:314:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1034:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'FetchError',
  message: 'request to http://content-api/v0/includeHtml.text failed, reason: getaddrinfo ENOTFOUND content-api content-api:80',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND' }
```

It won't impact system functionality in any way but it's good to have to test UI only feature in Gitlab.

### Problem reproduction steps

Deploy a test site in Gitlab using `UI Only Preview in Gitlab` option

**Comment by t83714** [comment]
fixed by https://github.com/magda-io/magda/pull/1843

**Comment by AlexGilleran** [comment]
:tada:
