### ISSUE TITLE
Search API timeout parameter probably need to be increased

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#1899]
### Problem description

When executing some complicated query i.e.:

https://dev.magda.io/search?organisation=Department%20of%20Health%20and%20Human%20Services&page=7&regionId=3&regionType=STE

`Elasticsearch` may take longer than 30 seconds (only on dev site) to process the request and search API will got the following timeout error:
```
[ERROR] [12/04/2018 00:22:00.427] [search-api-akka.actor.default-dispatcher-7000] [akka.actor.ActorSystemImpl(search-api)] Exception when searching
com.sksamuel.elastic4s.http.JavaClientExceptionWrapper: java.net.SocketTimeoutException
	at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient$$anon$1.onFailure(ElasticsearchJavaRestClient.scala:42)
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:608)
	at org.elasticsearch.client.RestClient$1.retryIfPossible(RestClient.java:399)
	at org.elasticsearch.client.RestClient$1.failed(RestClient.java:378)
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:419)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:375)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:263)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:492)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:213)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException
	... 11 more
```

It only happens to dev site and I guess because CPU resource is lower than production site.

One simple solution could be increasing the `Socket Timeout` parameter here (Probably change it to 60000 (60 seconds)):

https://github.com/magda-io/magda/blob/a17348eb67b1eb0afac51f118d5ec8018a0c9f04/magda-scala-common/src/main/resources/common.conf#L8

Put as low priority as it only happens to dev site.

**Comment by aneesha09** [comment]
Change to 1 minute using config on dev and production.

**Comment by t83714** [comment]
closed as the performance issue has been solved via PR https://github.com/magda-io/magda/pull/2116
