### ISSUE TITLE
Indexer throws an exception when processing invalid spatial data from `Australian Oceans Data Network`

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#1918]
### Problem description

When testing my pr for #983, I found out indexer throws an exception when processing invalid spatial data from `Australian Oceans Data Network`.

This seems an existing issue on Master branch and currently stop indexer from going further.

You will see the error on Master Dev site (and any other namespaces) indexer pod log as well:

```
[ERROR] [12/07/2018 01:26:18.954] [indexer-akka.actor.default-dispatcher-991] [akka.actor.ActorSystemImpl(indexer)] Exception encountered
java.lang.NumberFormatException: multiple points
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1914)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
```
Create as a seperate ticket so that we can create a seperate PR for it. 

#### Root Cause

Around this line: 
https://github.com/magda-io/magda/blob/0ef9cb63117731ee5b2eca4852cd811e3bbdf676/magda-scala-common/src/main/scala/au/csiro/data61/magda/model/Misc.scala#L140

We try to convert string like `123.8938` to a `double`. However, recent data from Australian Oceans Data Network has some data with more than one decimal places. i.e. `123.89.38`
Thus, produce the error above.

#### Proposed Solutions

- We should remove all `dots` after the first dot before call `_.double` to convert it. 
- Furthermore, considering low data quality in this area, we probably shouldn't let indexer stuck
  - The error was produced when a new webhook request is sent to indexer. Because of the error, this request will not be considered as `complete`. And you will see this log keep going and registry will not skip it to deliver the next one
  - Instead, we should:
    - Capture the error (around here: https://github.com/magda-io/magda/blob/0ef9cb63117731ee5b2eca4852cd811e3bbdf676/magda-scala-common/src/main/scala/au/csiro/data61/magda/model/Registry.scala#L265)
    - Print an error log
    - Index the dataset without spatial data (set spatial data field to `None`)

#### Example Dataset
Dateset ID:  `ds-aodn-9f8e77e3-8ea8-44cb-96b5-3cd2efb38e51`
Invalid Spatial data: 
```
POLYGON((141.3241 -46.9723, 147.53.08 -46.9723, 147.53.08 -43.0053, 141.3241 -43.0053, 141.3241 -46.9723))
```

**Comment by t83714** [comment]
Will probably look at this while work on my PR for 983 (as it stops me from creating a full indexed test site).
