### ISSUE TITLE
Indexer fails with "Object is missing required member 'id'"

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2484]
**Describe the bug**
Since we added the Add Dataset flow, the dev indexer has stalled with this error:

```
[ERROR] [09/16/2019 03:52:44.081] [indexer-akka.actor.default-dispatcher-7] [akka.actor.ActorSystemImpl(indexer)] Exception encountered
spray.json.DeserializationException: Object is missing required member 'id'
	at spray.json.package$.deserializationError(package.scala:23)
	at spray.json.ProductFormats$class.fromField(ProductFormats.scala:61)
	at au.csiro.data61.magda.indexer.external.registry.WebhookApi.fromField(WebhookApi.scala:22)
	at spray.json.ProductFormatsInstances$$anon$5.read(ProductFormatsInstances.scala:133)
	at spray.json.ProductFormatsInstances$$anon$5.read(ProductFormatsInstances.scala:121)
	at spray.json.JsValue.convertTo(JsValue.scala:33)
	at au.csiro.data61.magda.model.RegistryConverters$$anonfun$24.apply(Registry.scala:170)
	at au.csiro.data61.magda.model.RegistryConverters$$anonfun$24.apply(Registry.scala:167)
	at scala.Option.map(Option.scala:146)
	at au.csiro.data61.magda.model.RegistryConverters$class.convertRegistryDataSet(Registry.scala:167)
	at au.csiro.data61.magda.indexer.external.registry.WebhookApi.convertRegistryDataSet(WebhookApi.scala:22)
	at au.csiro.data61.magda.indexer.external.registry.WebhookApi$$anonfun$1$$anonfun$apply$1$$anonfun$7$$anonfun$8.apply(WebhookApi.scala:70)
	at au.csiro.data61.magda.indexer.external.registry.WebhookApi$$anonfun$1$$anonfun$apply$1$$anonfun$7$$anonfun$8.apply(WebhookApi.scala:69)
	at scala.collection.immutable.List.map(List.scala:284)
	at au.csiro.data61.magda.indexer.external.registry.WebhookApi$$anonfun$1$$anonfun$apply$1$$anonfun$7.apply(WebhookApi.scala:69)
	at au.csiro.data61.magda.indexer.external.registry.WebhookApi$$anonfun$1$$anonfun$apply$1$$anonfun$7.apply(WebhookApi.scala:66)
	at au.csiro.data61.magda.indexer.external.registry.WebhookApi$$anonfun$1$$anonfun$apply$1$$anonfun$9.apply(WebhookApi.scala:80)
	at au.csiro.data61.magda.indexer.external.registry.WebhookApi$$anonfun$1$$anonfun$apply$1$$anonfun$9.apply(WebhookApi.scala:80)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.util.NoSuchElementException: key not found: id
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.immutable.TreeMap.default(TreeMap.scala:48)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.immutable.TreeMap.apply(TreeMap.scala:48)
	at spray.json.ProductFormats$class.fromField(ProductFormats.scala:58)
	... 31 more
```

This is bad for two reasons:
- We're producing a record that can't be indexed.
- A bad record causes the indexer to pause permanently.

**To Reproduce**
Either simply look at the dev.magda.io indexer, or create a new dataset through /dataset/add.

**Expected behavior**
1. Add Dataset shouldn't be creating broken datasets.
2. Even if the dataset is broken, the indexer should skip over it and log an error rather than stopping altogether.

**Comment by t83714** [comment]
This issue is actually caused by #2505 
But we probably still should make sure indexer not fail because of this invalid data.
Will created a PR shortly
