### ISSUE TITLE
Indexer docker image fails to push

### ISSUE THREAD

**Issue by sajidanower23** [magda-io/magda#2852]
**Describe the bug**
When pushing the docker images via lerna, magda-indexer's docker image fails to push.

**To Reproduce**

1. Go to project root
1. Run `yarn lerna run build --stream --concurrency=1 --include-dependencies`
1. Run `eval $(minikube docker-env)`
1. Run `yarn lerna run docker-build-local --stream --concurrency=4 --include-dependencies`

**Expected behavior**
The docker push should not fail with a 500.

**Logs**
```
@magda/indexer: [info] Sending build context to Docker daemon  211.3MB
@magda/indexer: [info] Step 1/4 : FROM java
@magda/indexer: [info]  ---> d23bdf5b1b1b
@magda/indexer: [info] Step 2/4 : ENTRYPOINT ["\/app\/bin\/magda-indexer"]
@magda/indexer: [info]  ---> Using cache
@magda/indexer: [info]  ---> 5208ede8274b
@magda/indexer: [info] Step 3/4 : COPY 0/stage /app
@magda/indexer: [info]  ---> Using cache
@magda/indexer: [info]  ---> 79fe6ebee201
@magda/indexer: [info] Step 4/4 : EXPOSE 80
@magda/indexer: [info]  ---> Using cache
@magda/indexer: [info]  ---> 7a5bef5cbc6f
@magda/indexer: [info] Successfully built 7a5bef5cbc6f
@magda/indexer: [info] Tagging image 7a5bef5cbc6f with name: localhost:5000/data61/magda-indexer:latest
@magda/indexer: [info] Pushing docker image with name: 'localhost:5000/data61/magda-indexer:latest'
@magda/indexer: [info] The push refers to repository [localhost:5000/data61/magda-indexer]
@magda/indexer: [info] 9751633ca4b2: Preparing
@magda/indexer: [info] 35c20f26d188: Preparing
@magda/indexer: [info] c3fe59dd9556: Preparing
@magda/indexer: [info] 6ed1a81ba5b6: Preparing
@magda/indexer: [info] a3483ce177ce: Preparing
@magda/indexer: [info] ce6c8756685b: Preparing
@magda/indexer: [info] 30339f20ced0: Preparing
@magda/indexer: [info] 0eb22bfb707d: Preparing
@magda/indexer: [info] a2ae92ffcd29: Preparing
@magda/indexer: [info] 30339f20ced0: Waiting
@magda/indexer: [info] 0eb22bfb707d: Waiting
@magda/indexer: [info] a2ae92ffcd29: Waiting
@magda/indexer: [info] ce6c8756685b: Waiting
@magda/indexer: [info] a3483ce177ce: Layer already exists
@magda/indexer: [info] 9751633ca4b2: Layer already exists
@magda/indexer: [info] 35c20f26d188: Layer already exists
@magda/indexer: [info] c3fe59dd9556: Layer already exists
@magda/indexer: [info] 6ed1a81ba5b6: Layer already exists
@magda/indexer: [info] ce6c8756685b: Layer already exists
@magda/indexer: [info] a2ae92ffcd29: Layer already exists
@magda/indexer: [info] 0eb22bfb707d: Layer already exists
@magda/indexer: [info] 30339f20ced0: Layer already exists
@magda/indexer: [info] [DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the localhost:5000 registry NOW to avoid future disruption. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
@magda/indexer: [info] received unexpected HTTP status: 500 Internal Server Error
@magda/indexer: [error] java.lang.RuntimeException: Failed to push
@magda/indexer: [error] 	at scala.sys.package$.error(package.scala:30)
@magda/indexer: [error] 	at sbtdocker.DockerPush$.apply(DockerPush.scala:42)
@magda/indexer: [error] 	at sbtdocker.DockerPush$.$anonfun$apply$1(DockerPush.scala:17)
@magda/indexer: [error] 	at sbtdocker.DockerPush$.$anonfun$apply$1$adapted(DockerPush.scala:16)
@magda/indexer: [error] 	at scala.collection.immutable.List.foreach(List.scala:392)
@magda/indexer: [error] 	at sbtdocker.DockerPush$.apply(DockerPush.scala:16)
@magda/indexer: [error] 	at sbtdocker.DockerSettings$.$anonfun$baseDockerSettings$2(DockerSettings.scala:24)
@magda/indexer: [error] 	at sbtdocker.DockerSettings$.$anonfun$baseDockerSettings$2$adapted(DockerSettings.scala:19)
@magda/indexer: [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
@magda/indexer: [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
@magda/indexer: [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
@magda/indexer: [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
@magda/indexer: [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
@magda/indexer: [error] 	at sbt.Execute.work(Execute.scala:290)
@magda/indexer: [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
@magda/indexer: [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
@magda/indexer: [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
@magda/indexer: [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
@magda/indexer: [error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
@magda/indexer: [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
@magda/indexer: [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
@magda/indexer: [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
@magda/indexer: [error] 	at java.base/java.lang.Thread.run(Thread.java:834)
@magda/indexer: [error] (indexer / dockerPush) Failed to push
@magda/indexer: [error] Total time: 7 s, completed 3 Jun. 2020, 10:05:55 am
@magda/indexer: error Command failed with exit code 1.
@magda/indexer: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run docker-build-local exited 1 in '@magda/indexer'
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by t83714** [comment]
@sajidanower23 I guess we can confirm this one is a local issue that has something do with insufficient hard drive storage?

**Comment by sajidanower23** [comment]
Yes, that's correct. Looking at the docker-registry logs, it appears that there was no space left in my minikube instance.
Space can be cleaned up with `docker image prune -f`.
