### ISSUE TITLE
Dev site search API fails to parse Es response

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2885]
**Describe the bug**

Go to `https://dev.magda.io/search` and you will see the following on screen:

![image](https://user-images.githubusercontent.com/674387/85651209-b7c58880-b6ea-11ea-9a69-f72cb0acc35f.png)

and the following logs printed from search API pod:

```
search-api spray.json.DeserializationException: Expected Collection as JsArray, but got "ASICA"                                    │
│ search-api     at spray.json.package$.deserializationError(package.scala:23)                                                       │
│ search-api     at spray.json.ProductFormats.fromField(ProductFormats.scala:63)                                                     │
│ search-api     at spray.json.ProductFormats.fromField$(ProductFormats.scala:51)                                                    │
│ search-api     at au.csiro.data61.magda.search.elasticsearch.ElasticSearchImplicits$.fromField(ElasticSearchImplicits.scala:19)    │
│ search-api     at spray.json.ProductFormatsInstances$$anon$17.read(ProductFormatsInstances.scala:616)                              │
│ search-api     at spray.json.ProductFormatsInstances$$anon$17.read(ProductFormatsInstances.scala:589)                              │
│ search-api     at spray.json.JsValue.convertTo(JsValue.scala:33)                                                                   │
│ search-api     at au.csiro.data61.magda.model.misc.Protocols$dataSetFormat$.$anonfun$convertOptionField$1(Misc.scala:677)          │
│ search-api     at scala.Option.flatMap(Option.scala:271)                                                                           │
│ search-api     at au.csiro.data61.magda.model.misc.Protocols$dataSetFormat$.convertOptionField(Misc.scala:674)                     │
│ search-api     at au.csiro.data61.magda.model.misc.Protocols$dataSetFormat$.read(Misc.scala:705)                                   │
│ search-api     at au.csiro.data61.magda.model.misc.Protocols$dataSetFormat$.read(Misc.scala:632)                                   │
│ search-api     at spray.json.JsValue.convertTo(JsValue.scala:33)                                                                   │
│ search-api     at au.csiro.data61.magda.search.elasticsearch.ElasticSearchImplicits$DataSetHitAs$.$anonfun$read$2(ElasticSearchImp │
│ search-api     at scala.util.Try$.apply(Try.scala:213)                                                                             │
│ search-api     at au.csiro.data61.magda.search.elasticsearch.ElasticSearchImplicits$DataSetHitAs$.read(ElasticSearchImplicits.scal │
│ search-api     at com.sksamuel.elastic4s.Hit.safeTo(Hit.scala:34)                                                                  │
│ search-api     at com.sksamuel.elastic4s.Hit.safeTo$(Hit.scala:34)                                                                 │
│ search-api     at com.sksamuel.elastic4s.http.search.SearchHit.safeTo(responses.scala:12)                                          │
│ search-api     at com.sksamuel.elastic4s.Hit.to(Hit.scala:27)                                                                      │
│ search-api     at com.sksamuel.elastic4s.Hit.to$(Hit.scala:27)                                                                     │
│ search-api     at com.sksamuel.elastic4s.http.search.SearchHit.to(responses.scala:12) 
```

Could be related to #2868 and [this PR](https://github.com/magda-io/magda/pull/2878)

**Comment by AlexGilleran** [comment]
Seems to be OK now, although there are some other issues holding up ingestion into the search index.
