### ISSUE TITLE
QSpatial CSW Connector is failing

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#893]
### Problem description
We recently added QSpatial as a source but the CSW Connector can't handle it. It fails with this error:

```
Requesting http://qldspatial.information.qld.gov.au/catalogueadmin/csw?service=CSW&version=2.0.2&request=GetRecords&constraintLanguage=FILTER&constraint_language_version=1.1.0&resultType=results&elementsetname=full&outputschema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&typeNames=gmd%3AMD_Metadata&startPosition=1&maxRecords=100
Received@0
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property '0' of undefined
```

### Problem reproduction steps
Run the QSpatial connector.

**Comment by aneesha09** [comment]
Investigate why this is happening, timeboxed to 2 days

**Comment by nahidakbar** [comment]
@AlexGilleran @aneesha09 Investigated it for half a day and failed to reproduce the problem.
WIP is in issue/893 branch

**Comment by AlexGilleran** [comment]
🎉 👍

**Comment by nahidakbar** [comment]
```
TypeError: Cannot read property '0' of undefined at CswTransformer.getRawDatasetId (/home/god/magda/magda-csw-connector/dist/CswTransformer.js:49:47) at CswTransformer.getIdFromJsonDataset (/home/god/magda/magda-csw-connector/dist/CswTransformer.js:17:25) at CswTransformer.datasetJsonToRecord (/home/god/magda/magda-typescript-common/dist/JsonTransformer.js:49:25) at JsonConnector.<anonymous> (/home/god/magda/magda-typescript-common/dist/JsonConnector.js:88:49) at Generator.next (<anonymous>) at /home/god/magda/magda-typescript-common/dist/JsonConnector.js:7:71 at new Promise (<anonymous>) at __awaiter (/home/god/magda/magda-typescript-common/dist/JsonConnector.js:3:12) at AsyncPage_1.forEachAsync (/home/god/magda/magda-typescript-common/dist/JsonConnector.js:87:88) at /home/god/magda/magda-typescript-common/dist/AsyncPage.js:115:19
```
Noticed this while doing another issue.  If this is the exception observed, it is due to invalid metadata. Observed this when fileIdentifier was missing which iirc was mandatory in ISO19115.

**Comment by AlexGilleran** [comment]
Yeah I'm seeing that too :(.

We need to handle this in a way that doesn't crash the connector.
